image: ruby:3.0

variables:
  JEKYLL_ENV: production

cache:
  paths:
    - vendor/

before_script:
  - gem install bundler
  - bundle config set --local path 'vendor'
  - bundle install

pages:
  stage: deploy
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - main

# Test build job (optional)
test:
  stage: test
  script:
    - bundle exec jekyll build -d test
  except:
    - main
