# Jekyll with Minimal Mistakes Remote Theme
title: "Hysteresis: When Matter Learns to Remember"
subtitle: "Electromagnetic field visualization through cybernetic organisms"
description: "Research into autonomous synthetic organisms developing environmental coupling and communication protocols"
url: "https://hysteresis.ca"
baseurl: ""

# Remote Theme (no gem needed)
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "default"

# Site Author
author:
  name: "Hysteresis Research"
  bio: "Cybernetic coupling research through autonomous synthetic organisms"
  location: "Research Laboratory"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-remote-theme

# Reading Files
include:
  - .htaccess
  - _pages

# Exclude from processing
exclude:
  - vendor/
  - .bundle/
  - Gemfile
  - Gemfile.lock
  - .gitlab-ci.yml
  - code/
  - config.yaml
  - content/
  - node_modules/
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .sass-cache

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
